### ISSUE TITLE
Add a table with the summary of clinical data content

### ISSUE THREAD

**Issue by fedorov** [fedorov/actcianable#57]
I think we should do the following:

* add a scraper that identifies links to clinical data attachments in wiki pages and creates a JSON file (something like this one perhaps: https://github.com/fedorov/actcianable/blob/master/output/image_analyses_details.json) that contains:
  * collection ID and DOI (to link with other related information)
  * link to the clinical table artifact
  * format
  * hash of the file (to track changes)
  * manually curated field with the notes
  * ... anything else? ...
* when scraper is executed, it should not overwrite manually curated notes in JSON!
* the way I did it in the past, I would run the script once manually first, add JSON to the repo, add manual notes, then add the scraper to [this section](https://github.com/fedorov/actcianable/blob/master/.github/workflows/manual.yml#L32) in the GitHub Actions script, and make sure it outputs into that JSON file in the repo - this way it will be picked up as changed file by git, and will be included in the pull request in github action
* given the content of the JSON file, will need to add another section to the index.html [here](https://github.com/fedorov/actcianable/blob/master/index.html#L112-L127), so that the table in the web page is automatically populated from JSON

Does this make sense @G-White-ISB?

**Comment by G-White-ISB** [comment]
Sounds goods

**Comment by fedorov** [comment]
resolved by #63
