### ISSUE TITLE
Fix false alarms triggered by the clinical data scraper

### ISSUE THREAD

**Issue by fedorov** [fedorov/actcianable#99]
See #98 - the only "updates" are those in the JSON file produced by the scraper. Why are those dates different?

![image](https://user-images.githubusercontent.com/313942/179803028-ff3c3c99-672a-4e1a-bc72-a5a5f265b437.png)

**Comment by G-White-ISB** [comment]
The notes attribute in the clinical_collections.json file are retrieved from the clinical_notes.json file that I write which includes details for how to parse each collection. If a collection is not present in the clinical_notes.json file then I have not noticed this collection yet. To highlight this I had the scrapper add the note 'new collection detected as of' +current date for this collection in the clinical_collections file, anticipating that I would quickly follow up with this collection. I have changed this to a static note: 'collection not yet curated in idc'. I've also looked at the 2 collections, FDG-PET-CT-Lesions and UPENN-GBM and added notes for them

**Comment by fedorov** [comment]
Today's PR #100 seemed to indicate updates to clinical data, but I am not sure.

Let's see what happens tomorrow. You did try to rerun the scraper and check if repeated invocations do not trigger repeated updates, right?

**Comment by fedorov** [comment]
@G-White-ISB `get_clinical` scraper is failing, can you take a look: https://github.com/fedorov/actcianable/runs/7574413251?check_suite_focus=true#step:5:2257 ?

**Comment by G-White-ISB** [comment]
It's failing on scraping CPTAC-UCEC. They have moved the CPTAC pages but have not updates the link in their collections list:

https://wiki.cancerimagingarchive.net/display/Public/CPTAC-UCEC

**Comment by fedorov** [comment]
We brought this up with TCIA at the IRCoCo meeting today. Apparently, someone messed up, and they will be fixing the CPTAC-UCEC page. 

This issue should hopefully be resolved by #101.
